version: "3"

services:
  passwords:
    image : dgoldstein1/passwordservice:latest
    expose:
      - 8080
      - 10000
      - 10001
    ports: 
      - "8080:8080"
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./docker/passwordservice/certs/:/opt/services/passwordservice/certs/
      - ./cmd:/go/src/github.com/dgoldstein1/passwordservice/cmd
      - ./docs/api:/opt/services/passwordservice/docs
      - ./protobuf:/go/src/github.com/dgoldstein1/passwordservice/protobuf
      - ./settings.toml:/etc/passwordservice/settings.toml

  mongodb:
    image: mongo:3.2.1
    ports:
      - "27017:27017"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null